apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: msa-service
  labels:
    app: msa-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: chupdachups/account-service:latest
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: msa-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
---
#kind: Ingress
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: webserver
#  namespace: spring-cloud
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#spec:
#  rules:
#  - host: mywebserver.io
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: webserver
#            port:
#              number: 80