-- -----------------------------------------------------
-- Table `ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACCOUNT`
(
  `ACCOUNT_ID`				VARCHAR(255) generated by default as identity,
  `EMAIL`					VARCHAR(255) NOT NULL,
  `FIRST_NAME`				VARCHAR(255) NOT NULL,
  `LAST_NAME`				VARCHAR(255) NOT NULL,
  `PASSWORD`				VARCHAR(255) NOT NULL,
  `ADDRESS1`				VARCHAR(255) NOT NULL,
  `ZIP`						VARCHAR(255) NOT NULL,
  `CREATED_AT`				TIMESTAMP    NULL,
  `UPDATED_AT`				TIMESTAMP    NULL,
  `LATEST_LOGIN_AT`     	TIMESTAMP    NULL,
  `ROLE`					VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
);
-- -----------------------------------------------------
-- Table `PRODUCT`
-- -----------------------------------------------------
--CREATE TABLE IF NOT EXISTS `PRODUCT`
--(
--  `PRODUCT_ID`				VARCHAR(255) generated by default as identity,
--  `PRODUCT_NAME`			VARCHAR(255) NOT NULL,
--  `ADDRESS`					VARCHAR(255) NOT NULL,
--  `DETAIL_ADDRESS`			VARCHAR(255) NOT NULL,
--  `PRICE`					VARCHAR(255) NOT NULL,
--  `CREATED_AT`				TIMESTAMP    NULL,
--  `UPDATED_AT`				TIMESTAMP    NULL,
--  PRIMARY KEY (`PRODUCT_ID`)
--);
-- -----------------------------------------------------
-- Table `USER_ROLE`
-- -----------------------------------------------------
--CREATE TABLE IF NOT EXISTS `USER_ROLE`
--(
--  `ROLE_ID`             VARCHAR(255) NOT NULL,
--  `USER_ID`             VARCHAR(255) NOT NULL,
--  `ROLE`                VARCHAR(255) NOT NULL,
--  `AUTHORIZED_AT`       TIMESTAMP    NULL,
--  PRIMARY KEY (`ROLE_ID`)
--);